version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - E:/Jewel/Project_java/Back-end/init/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - E:/Jewel/Project_java/Back-end/init/elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - E:/Jewel/Project_java/Back-end/init/logs/:/usr/share/logstash/logs/
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - E:/Jewel/Project_java/Back-end/init/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
